version: '3'

services:
  mongodb:
    image: mongo
    container_name: ii2-mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: ii2-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ii2db
      - PORT=5000
      - JWT_SECRET=supersecretkey123
      - CLIENT_URL=http://172.7.189.16:3001

  frontend:
    build: ./frontend
    container_name: ii2-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
